version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Validating CloudFormation template..."
      - |
        if ! aws cloudformation validate-template --template-body file://template.yaml; then
          echo "Template validation failed. Exiting..."
          exit 1
        fi
  post_build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - |
        if ! aws cloudformation deploy --template-file template.yaml --stack-name TwoTierStack --capabilities CAPABILITY_NAMED_IAM --region us-east-1; then
          echo "Stack deployment failed. Exiting..."
          exit 1
        fi

artifacts:
  files:
    - template.yaml
